dist: trusty
language: android

git:
  depth: false

before_install:
  - sudo apt-get -y install xsltproc xml-twig-tools

android:
  components:
    # Update Android SDK tools
    - tools
    - platform-tools

    # Build tools
    - build-tools-29.0.3

    # SDK version
    - android-29

    # Additional Google components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
    - $HOME/.android/build-cache
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

jobs:	
  fast_finish: true
  include:
    - script: ./gradlew test
      if: type = pull_request
    - script: ./gradlew lint
      if: type = pull_request
    - stage: run_ci_pull_request_assemble
      if: type = pull_request
      script: ./gradlew assembleDebug
    - stage: run_ci_fastlane
      before_install:
        - rvm install 2.6.3
        - bundle install
        - fastlane install_plugins
      script: bundle exec fastlane testing  
      if: type (NOT type IN (pull_request))