language: android
# you MUST mention trusty https://docs.travis-ci.com/user/languages/android/
dist: trusty

android:
  components:
    #- tools
    #- platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository # for design library
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+    

before_script:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_TAG
    
script:
    - ./gradlew clean

stages:
    - 'Lint'
    - 'Test'
        
jobs:
  include:
    - stage: 'Lint'
      name: 'Static analysis check'
      script:
        - ./gradlew lint

    - stage: 'Test'
      name: 'Unit test'
      script:
        - ./gradlew test
