dist: trusty
language: android

git:
  depth: false

android:
  components:
    # Update Android SDK tools
    - tools
    - platform-tools

    # Build tools
    - build-tools-29.0.3

    # SDK version
    - android-29

    # Additional Google components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
    - $HOME/.android/build-cache
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

jobs:	
  include:	
    - script:	./gradlew lint
      name: 'Static analysis check'	
    - script: ./gradlew test    
      name: 'Unit tests'
      after_failure: ./junit-errors-to-stdout.sh
