language: android
# you MUST mention trusty https://docs.travis-ci.com/user/languages/android/
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository # for design library

before_install:
    - yes | sdkmanager "platforms;android-26"    

before_script:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_TAG

script:
    - ./gradlew lint
    - ./gradlew test
